name: Deploy to Staging on Push

# Controls when the action will run.
# This workflow runs on pushes to the "staging" branch.
on:
  push:
    branches:
      - staging

jobs:
  # This workflow contains a single job called "build_and_deploy_staging"
  build_and_deploy_staging:
    # The name of the job, and the environment it runs in
    name: Build and Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging # Use secrets from the "staging" GitHub Environment

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # 2. Sets up the Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. Installs dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Install function dependencies
      - name: Install Function Dependencies
        run: cd functions && npm ci

      # 5. Analyzes the code for style consistency and potential errors
      - name: Lint Code
        run: npm run lint

      # 6. Executes the test suite
      - name: Run Unit & Integration Tests
        run: npm test:all

      # 7. Create .env file
      - name: Create .env file
        run: |
          echo REACT_APP_FIREBASE_API_KEY=${{ vars.REACT_APP_FIREBASE_API_KEY }} >> .env
          echo REACT_APP_FIREBASE_AUTH_DOMAIN=${{ vars.REACT_APP_FIREBASE_AUTH_DOMAIN }} >> .env
          echo REACT_APP_FIREBASE_PROJECT_ID=${{ vars.REACT_APP_FIREBASE_PROJECT_ID }} >> .env
          echo REACT_APP_FIREBASE_STORAGE_BUCKET=${{ vars.REACT_APP_FIREBASE_STORAGE_BUCKET }} >> .env
          echo REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ vars.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }} >> .env
          echo REACT_APP_FIREBASE_APP_ID=${{ vars.REACT_APP_FIREBASE_APP_ID }} >> .env
          echo ALLOWED_ORIGIN_WEB=${{ vars.ALLOWED_ORIGIN_WEB }} >> functions/.env
          echo ALLOWED_ORIGIN_FB=${{ vars.ALLOWED_ORIGIN_FB }} >> functions/.env
          echo DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }} >> functions/.env
          echo DISCORD_CLIENT_SECRET=${{ secrets.DISCORD_CLIENT_SECRET }} >> functions/.env
          echo DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} >> functions/.env
          echo DISCORD_CHANNEL_ID=${{ vars.DISCORD_CHANNEL_ID }} >> functions/.env

      # 8. Builds the React application for production
      - name: Build
        run: npm run build

      # 9. Authenticate to Google Cloud using the staging secret
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}'

      # 10. Deploy to Firebase Staging
      - name: Deploy to Firebase Staging
        run: |
          npx firebase deploy --only functions,hosting,firestore --project numenor-freight-staging
